grails-app/domain/org/gr8conf/ScheduledItem.groovy
package org.gr8conf

import cacoethes.Conference
import cacoethes.Submission
class ScheduledItem {

    String name
    String icon
    Conference conference
    Track track
    Slot slot

    Submission submission
    Date dateCreated
    Date lastUpdated

    static nameOrSubmissionValidtor = { val, obj ->
        if (!obj.submission && !obj.name) {
            return ['nullNameAndSubmission']
        }
        if (obj.submission && obj.name) {
            return['populatedNameAndSubmission']
        }
    } 
    static constraints = {
        icon nullable: true
        submission nullable: true, validator: nameOrSubmissionValidtor
        name nullable: true, validator: nameOrSubmissionValidtor
        dateCreated nullable: true
        lastUpdated nullable: true
    }
}

grails-app/controllers/org/gr8conf/ScheduledItemController.groovy
package org.gr8conf

import cacoethes.Conference
import grails.plugin.springsecurity.annotation.Secured
import org.springframework.dao.DataIntegrityViolationException

@Secured(['ROLE_ADMIN'])
class ScheduledItemController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list(Long conferenceId) {
        def query = ScheduledItem.where {
            submission == null
        }
        if (conferenceId) {
            query = query.where {
                conference.id == conferenceId
            }
        }
        [scheduledItemInstanceList: query.findAll(), scheduledItemInstanceTotal: ScheduledItem.count()]
    }

    def create(Long conferenceId) {
        Conference conference = Conference.get(conferenceId)
        [scheduledItemInstance: new ScheduledItem(params), 
         conferenceId: conferenceId,
         tracks: Track.findAllByConference(conference),
         slots: Slot.findAllByConference(conference)
        ]
    }

    def save(Long conferenceId) {
        def scheduledItemInstance = new ScheduledItem(params)
        def existing = ScheduledItem.findByTrackAndSlot(scheduledItemInstance.track, scheduledItemInstance.slot)
        if (!scheduledItemInstance.save(flush:true)) {
            render(view: "create", model: [scheduledItemInstance: scheduledItemInstance])
            return
        }
        existing?.delete(flush: true)


        flash.message = message(code: 'default.created.message', args: [message(code: 'scheduledItem.label', default: 'ScheduledItem'), scheduledItemInstance.id])
        redirect(action: "show", id: scheduledItemInstance.id)
    }

    def show(Long id) {
        def scheduledItemInstance = ScheduledItem.get(id)
        if (!scheduledItemInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'scheduledItem.label', default: 'ScheduledItem'), id])
            redirect(action: "list")
            return
        }

        [scheduledItemInstance: scheduledItemInstance]
    }

    def edit(Long id) {
        def scheduledItemInstance = ScheduledItem.get(id)
        if (!scheduledItemInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'scheduledItem.label', default: 'ScheduledItem'), id])
            redirect(action: "list")
            return
        }
        [scheduledItemInstance: scheduledItemInstance, 
         conferenceId: scheduledItemInstance.conference.id,
         tracks: Track.findAllByConference(scheduledItemInstance.conference),
         slots: Slot.findAllByConference(scheduledItemInstance.conference)
        ]
    }

    def update(Long id, Long version) {
        def scheduledItemInstance = ScheduledItem.get(id)
        if (!scheduledItemInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'scheduledItem.label', default: 'ScheduledItem'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (scheduledItemInstance.version > version) {
                scheduledItemInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                          [message(code: 'scheduledItem.label', default: 'ScheduledItem')] as Object[],
                          "Another user has updated this ScheduledItem while you were editing")
                render(view: "edit", model: [scheduledItemInstance: scheduledItemInstance])
                return
            }
        }

        scheduledItemInstance.properties = params

        if (!scheduledItemInstance.save(flush: true)) {
            render(view: "edit", model: [scheduledItemInstance: scheduledItemInstance])
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'scheduledItem.label', default: 'ScheduledItem'), scheduledItemInstance.id])
        redirect(action: "show", id: scheduledItemInstance.id)
    }

    def delete(Long id) {
        def scheduledItemInstance = ScheduledItem.get(id)
        if (!scheduledItemInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'scheduledItem.label', default: 'ScheduledItem'), id])
            redirect(action: "list")
            return
        }

        try {
            scheduledItemInstance.delete(flush: true)
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'scheduledItem.label', default: 'ScheduledItem'), id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException ignored) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'scheduledItem.label', default: 'ScheduledItem'), id])
            redirect(action: "show", id: id)
        }
    }
}

grails-app/views/scheduledItem/_form.gsp
<f:with bean="${scheduledItemInstance}">
    <g:set var="conferenceId" value="${scheduledItemInstance.conferenceId?:params.conferenceId}"/>
    <f:field property="name"/>
    <f:field property="track"/>
    <f:field property="slot"/>
    <g:hiddenField name="conference" value="${conferenceId}"/>
</f:with>

grails-app/views/scheduledItem/create.gsp
<%@ page import="org.gr8conf.ScheduledItem" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'scheduledItem.label', default: 'ScheduledItem')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<div id="create-scheduledItem" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${scheduledItemInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${scheduledItemInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form action="save" >
				<fieldset class="form">
                    <g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/scheduledItem/edit.gsp
<%@ page import="org.gr8conf.ScheduledItem" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'scheduledItem.label', default: 'ScheduledItem')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<div id="edit-scheduledItem" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${scheduledItemInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${scheduledItemInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${scheduledItemInstance?.id}" />
				<g:hiddenField name="version" value="${scheduledItemInstance?.version}" />
				<fieldset class="form">
                    <g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/scheduledItem/index.gsp
<%@ page import="org.gr8conf.ScheduledItem" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'scheduledItem.label', default: 'ScheduledItem')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-scheduledItem" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-scheduledItem" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="scheduledItem.submission.label" default="Submission" /></th>
					
						<g:sortableColumn property="name" title="${message(code: 'scheduledItem.name.label', default: 'Name')}" />
					
						<th><g:message code="scheduledItem.conference.label" default="Conference" /></th>
					
						<th><g:message code="scheduledItem.slot.label" default="Slot" /></th>
					
						<th><g:message code="scheduledItem.track.label" default="Track" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${scheduledItemInstanceList}" status="i" var="scheduledItemInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${scheduledItemInstance.id}">${fieldValue(bean: scheduledItemInstance, field: "submission")}</g:link></td>
					
						<td>${fieldValue(bean: scheduledItemInstance, field: "name")}</td>
					
						<td>${fieldValue(bean: scheduledItemInstance, field: "conference")}</td>
					
						<td>${fieldValue(bean: scheduledItemInstance, field: "slot")}</td>
					
						<td>${fieldValue(bean: scheduledItemInstance, field: "track")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${scheduledItemInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/scheduledItem/list.gsp
<%@ page import="org.gr8conf.ScheduledItem" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'scheduledItem.label', default: 'ScheduledItem')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<div id="list-scheduledItem" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table class="table table-bordered">
				<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'scheduledItem.name.label', default: 'Name')}" />
					
						<th><g:message code="scheduledItem.conference.label" default="Conference" /></th>
					
						<th><g:message code="scheduledItem.slot.label" default="Slot" /></th>
					
						<th><g:message code="scheduledItem.track.label" default="Track" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${scheduledItemInstanceList}" status="i" var="scheduledItemInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${scheduledItemInstance.id}">${fieldValue(bean: scheduledItemInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: scheduledItemInstance, field: "conference")}</td>
					
						<td>${fieldValue(bean: scheduledItemInstance, field: "slot")}</td>
					
						<td>${fieldValue(bean: scheduledItemInstance, field: "track")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${scheduledItemInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/scheduledItem/show.gsp
<%@ page import="org.gr8conf.ScheduledItem" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'scheduledItem.label', default: 'ScheduledItem')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>

		<div id="show-scheduledItem" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			
				<g:if test="${scheduledItemInstance?.submission}">
                    <f:display bean="${scheduledItemInstance}" property="submission">
					
						<g:link controller="submission" action="show" id="${scheduledItemInstance?.submission?.id}">${scheduledItemInstance?.submission?.encodeAsHTML()}</g:link>
					
                    </f:display>
				</g:if>
			
				<g:if test="${scheduledItemInstance?.name}">
                    <f:display bean="${scheduledItemInstance}" property="name">
					
						<g:fieldValue bean="${scheduledItemInstance}" field="name"/>
					
                    </f:display>
				</g:if>
			
				<g:if test="${scheduledItemInstance?.conference}">
                    <f:display bean="${scheduledItemInstance}" property="conference">
					
						<g:link controller="conference" action="show" id="${scheduledItemInstance?.conference?.id}">${scheduledItemInstance?.conference?.encodeAsHTML()}</g:link>
					
                    </f:display>
				</g:if>
			
				<g:if test="${scheduledItemInstance?.slot}">
                    <f:display bean="${scheduledItemInstance}" property="slot">
					
						<g:link controller="slot" action="show" id="${scheduledItemInstance?.slot?.id}">${scheduledItemInstance?.slot?.encodeAsHTML()}</g:link>
					
                    </f:display>
				</g:if>
			
				<g:if test="${scheduledItemInstance?.track}">
                    <f:display bean="${scheduledItemInstance}" property="track">
					
						<g:link controller="track" action="show" id="${scheduledItemInstance?.track?.id}">${scheduledItemInstance?.track?.encodeAsHTML()}</g:link>
					
                    </f:display>
				</g:if>
			
			</ol>
			<g:form>
				<class class="row">
                    <div class="col-lg-push-2 col-lg-10">
					<g:hiddenField name="id" value="${scheduledItemInstance?.id}" />
					<g:link class="edit btn btn-default" action="edit" id="${scheduledItemInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete btn btn-warning" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                    </div>
				</class>
			</g:form>
		</div>
	</body>
</html>